### ISSUE TITLE
Can't use multiple fonts simultaneously

### ISSUE THREAD

**Issue by BGauth1** [420verfl0w/MacroLibX#2]
I can't figure out how to use multiple fonts on one image/frame on rendering, I don't know if that's supposed to be possible, and if not I think it'd be a great addition. In any case, great, clean and fast code !

e.g:
```
int	my_loop(t_mlx *mlx)
{
	mlx_set_font(mlx->mlx, mlx->win, "font1.ttf");
	mlx_string_put(mlx->mlx, mlx->win, 200, 50, 0xFF00FFFF, "Hello im font1");
	mlx_set_font(mlx->mlx, mlx->win, "font2.ttf");
	mlx_string_put(mlx->mlx, mlx->win, 200, 100, 0xFF00FFFF, "Hi font1, im font2");
	return (0);
}

**Comment by Kbz-8** [comment]
As the font system works at the moment, it's not possible to use multiple fonts per image. The macrolibx string rendering system is really simple and isn't really intended for rendering a lot of text in different fonts, as it's quite heavy for the CPU to load a font and create the rendering data that will be used by the GPU.

I think I'll ask the students around me what they think of this addition and maybe I'll add it to the lib.

**Comment by Kbz-8** [comment]
the feature has been added to the master branch, you can now use multiple fonts per frames and even resize the default font
